version: '3.8'

networks:
  microservices-network:
    driver: bridge

volumes:
  auth_mysql_data:
  redis_data:
  problem_mysql_data:

services:

  mysql:
    image: mysql:8.4.7
    container_name: mysql
    networks:
      - microservices-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application_auth_db
    volumes:
      - auth_mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - microservices-network
    ports:
      - "6379:6379"

  config-server:
    build: ./config-server
    container_name: config-server
    networks:
      - microservices-network
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      retries: 10


  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    networks:
      - microservices-network
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
       test: ["CMD-SHELL", "wget -q --spider http://localhost:8761/ || exit 1"]
       interval: 5s
        retries: 20

  auth-service:
    build: ./auth-service
    networks:
      - microservices-network
    ports:
      - "8081:8081"
    environment:
      SPRING_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: native
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/application_auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
    depends_on:
      discovery-server:
        condition: service_started

  problem-mysql:
    image: mysql:8.4.7
    container_name: problem-mysql
    networks:
      - microservices-network
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application_problemdb
    
    volumes:
      - problem_mysql_data:/var/lib/mysql

  problem-service:
    build: ./problemservice
    networks:
      - microservices-network
    ports:
      - "8082:8082"
    environment:
      SPRING_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: native
      SPRING_DATASOURCE_URL: jdbc:mysql://problem-mysql:3306/application_problemdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      discovery-server:
        condition: service_started
      auth-service:
        condition: service_started    

  api-gateway:
    build: ./api-gateway
    container_name: apic
    networks:
      - microservices-network
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_URI: http://config-server:8888
      SPRING_PROFILES_ACTIVE: native
    depends_on:
      discovery-server:
        condition: service_started

  frontend:
    build:
      context: ./frontend/Rankx
    networks:
      - microservices-network
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
